# Dockerfile.prod
FROM node:22.3.0-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install && npm install pm2 -g  # Установка pm2 глобально
COPY . .
RUN npm run build
EXPOSE 4000
CMD ["pm2-runtime", "start", "npm", "--", "start"]
