version: "3.8"

services:
  frontend:
    build: .
    container_name: nuxt_frontend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "4040:4040"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
