# Используем базовый образ Node.js версии 22.3.0
FROM node:22.3.0-alpine as build-stage

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта
COPY . .

# Собираем проект
RUN npm run build

# Финальный образ
FROM node:22.3.0-alpine as production-stage

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем собранные файлы из предыдущего этапа
COPY --from=build-stage /app /app

# Устанавливаем PM2 для запуска приложения
RUN npm install pm2 -g

# Открываем порт
EXPOSE 4000

# Запускаем приложение с использованием PM2
CMD ["pm2-runtime", "start", "npm", "--", "start"]
